// <auto-generated />
using System;
using Clinica.Api.Domain.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Clinica.Api.Migrations
{
    [DbContext(typeof(ClinicaContext))]
    partial class ClinicaContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("utf8mb4_general_ci")
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.HasCharSet(modelBuilder, "utf8mb4");
            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Clinica.Api.Domain.Entities.Consulta", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("AgendamentoId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataHora")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("PacienteId")
                        .HasColumnType("char(36)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Consultas");
                });

            modelBuilder.Entity("Clinica.Api.Domain.Entities.ConsultaSintoma", b =>
                {
                    b.Property<Guid>("ConsultaId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("SintomaId")
                        .HasColumnType("char(36)");

                    b.HasKey("ConsultaId", "SintomaId");

                    b.HasIndex("SintomaId");

                    b.ToTable("ConsultaSintomas");
                });

            modelBuilder.Entity("Clinica.Api.Domain.Entities.Doenca", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Doencas");
                });

            modelBuilder.Entity("Clinica.Api.Domain.Entities.Sintoma", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("DoencaId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Prioridade")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DoencaId");

                    b.ToTable("Sintomas");
                });

            modelBuilder.Entity("Clinica.Api.Domain.Entities.ConsultaSintoma", b =>
                {
                    b.HasOne("Clinica.Api.Domain.Entities.Consulta", "Consulta")
                        .WithMany("Sintomas")
                        .HasForeignKey("ConsultaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Clinica.Api.Domain.Entities.Sintoma", "Sintoma")
                        .WithMany()
                        .HasForeignKey("SintomaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Consulta");

                    b.Navigation("Sintoma");
                });

            modelBuilder.Entity("Clinica.Api.Domain.Entities.Sintoma", b =>
                {
                    b.HasOne("Clinica.Api.Domain.Entities.Doenca", "Doenca")
                        .WithMany("Sintomas")
                        .HasForeignKey("DoencaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Doenca");
                });

            modelBuilder.Entity("Clinica.Api.Domain.Entities.Consulta", b =>
                {
                    b.Navigation("Sintomas");
                });

            modelBuilder.Entity("Clinica.Api.Domain.Entities.Doenca", b =>
                {
                    b.Navigation("Sintomas");
                });
#pragma warning restore 612, 618
        }
    }
}
